import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile('src/PSH_Automation.gs','utf8');
const ctx=vm.createContext({console,Date});
vm.runInContext(source,ctx,{filename:'PSH_Automation.gs'});
const review=ctx.pshNewAccuracyReview_('Bertha');
const water=vm.runInContext('PSH.WATER',ctx);
const wind=vm.runInContext('PSH.WIND',ctx);
assert.equal(ctx.pshAccuracyPct_(review),'N/A');
review.matched=48;
review.missing.push({id:'OFBM6',field:'Water level (ft)',group:'WATER-USGS',sheet:'Water Level'});
const sh={getRange:(row,col)=>({getDisplayValue:()=>col===14?'[AUTO-QC] E':'',getRichTextValue:()=>null,getFormula:()=>''})};
ctx.cellLink_=()=> 'https://example.org/source';
ctx.pshRecordMismatch_(review,{id:'PSIL1',g:'WATER-USGS',sheet:water,col:7,expected:3.88,tol:0.15},2.97,74,sh);
ctx.pshRecordMismatch_(review,{id:'KMSY',g:'ASOS',sheet:wind,col:11,expected:23,tol:1},21,12,sh);
assert.equal(review.mismatches.length,2);
assert.equal(review.mismatches[0].field,'Water level (ft)');
assert.equal(review.mismatches[1].field,'Sustained wind (kt)');
assert.equal(review.mismatches[0].qc,'[AUTO-QC] E');
assert.equal(review.mismatches[1].url,'https://example.org/source');
assert.equal(ctx.pshAccuracyPct_(review),'96.0%','Missing should not enter accuracy denominator');
assert.equal(review.missing.length,1);
assert.equal(review.matched+review.mismatches.length,50);
console.log('PASS: populated numeric agreement 48/50 (96.0%); missing excluded; provenance recorded.');
